[2021-07-20 21:44:09,980][tasks][28][ERROR][发送验证码短信[失败][ mobile: 19180525254/ ]]
[2021-07-20 21:45:16,092][tasks][28][ERROR][发送验证码短信[失败][ mobile: 19180525254/ ]]
[2021-08-24 16:10:32,215][views][81][ERROR][缺少code码，登录失败。]
[2021-08-24 16:11:12,851][views][81][ERROR][缺少code码，登录失败。]
[2021-08-28 18:29:29,597][views][81][ERROR][缺少code码，登录失败。]
[2021-08-28 18:30:21,133][views][81][ERROR][缺少code码，登录失败。]
[2021-08-28 18:35:55,307][views][81][ERROR][缺少code码，登录失败。]
[2021-08-28 18:36:19,789][views][81][ERROR][缺少code码，登录失败。]
[2021-08-28 18:36:24,002][views][81][ERROR][缺少code码，登录失败。]
[2021-10-09 23:37:47,597][views][319][ERROR][[xmind用例写作模板.xmind] - 模块 [合同管理] 中已存在用例 [用例名称 1]  状态: 可用]
[2021-10-25 11:20:44,806][views][283][ERROR][[#37893 资产-办公室电池明细报表优化.xmind]-[观星台] 下无模块 [资产数据]，请先添加]
[2021-10-25 11:43:42,829][views][374][ERROR][[#37893 资产-办公室电池明细报表优化.xmind] 用例导入完成！]
[2021-10-25 11:47:01,998][views][269][ERROR][Traceback (most recent call last):
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/backend/backend/apps/cases/views.py", line 266, in post
    ins_module = Module.objects.get(name=name, parent_id=None)
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
cases.models.Module.DoesNotExist: Module matching query does not exist.
]
[2021-10-25 11:47:16,199][views][269][ERROR][Traceback (most recent call last):
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/backend/backend/apps/cases/views.py", line 266, in post
    ins_module = Module.objects.get(name=name, parent_id=None)
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/zhangjian/PycharmProjects/AutomationTestPlat/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
cases.models.Module.DoesNotExist: Module matching query does not exist.
]
[2021-10-25 11:48:13,182][views][374][ERROR][[#37893 资产-办公室电池明细报表优化.xmind] 用例导入完成！]
[2021-10-25 11:50:39,840][views][374][ERROR][[#37893 资产-办公室电池明细报表优化.xmind] 用例导入完成！]
[2021-10-25 11:53:21,704][views][374][ERROR][[#37893 资产-办公室电池明细报表优化.xmind] 用例导入完成！]
[2021-10-26 12:08:10,010][views][283][ERROR][[#34535-商户线-支持子规则特殊付款新增门店.xmind]-[CRM] 下无模块 [商户管理]，请先添加]
[2021-10-26 12:09:03,525][views][347][ERROR][[#34535-商户线-支持子规则特殊付款新增门店.xmind] - [crm延长合作期限-有剩余付款金额和均摊金额-子规则新增门店] 校验异常:
 >{'expectation': [ErrorDetail(string='请确保这个字段不能超过 100 个字符。', code='max_length')]}]
[2021-10-26 12:18:31,621][views][378][ERROR][[#34535-商户线-支持子规则特殊付款新增门店.xmind] 用例导入完成！]
[2021-10-26 15:14:41,814][views][294][ERROR][[# 32355 商户线-审批原因标准化.xmind]-模块 [工作流] 下无模块 [预置审批理由] ，请先添加]
[2021-10-26 15:14:56,971][views][378][ERROR][[#34535-商户线-支持子规则特殊付款新增门店.xmind] 用例导入完成！]
